Creating The Stackable Layout
cgduncan7/browser-quiz-project-starter pull request #10
Opened 2021-11-13 20:42 UTC by ChrisFayad

2021-11-14 20:16 UTC, cgduncan7 requested changes

2021-11-14 20:16 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> -  nextQuestionButton.removeEventListener('click', nextQuestion);
This shouldn't be removed... try to only modify parts of the code you need to change

2021-11-15 15:27 UTC, cgduncan7 requested changes

2021-11-15 15:27 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
>    const currentQuestion = quizData.questions[quizData.currentQuestionIndex];
Do we use the `currentQuestion` anywhere?

2021-11-15 15:27 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
>    const questionContainer = getDOMElement(QUESTION_CONTAINER_ID);
Do we use `questionContainer`?

2021-11-15 15:27 UTC, cgduncan7 commented on src/init/initializeQuiz.js
> +  [...quizQuestions.children].forEach((question) => questionContainer.appendChild(question));
```suggestion
  quizQuestions.children.forEach((question) => questionContainer.appendChild(question));
```

I think you can just do this, right?

`[...[]] = []`

2021-11-15 15:27 UTC, cgduncan7 commented on src/views/questionViews.js
> +  buttonElement.addEventListener('click', nextQuestion);
We don't want this event listener here

2021-11-15 16:03 UTC, ChrisFayad commented on src/init/initializeQuiz.js
> +  [...quizQuestions.children].forEach((question) => questionContainer.appendChild(question));
Nope I think we need it because if I remove it I get the following erron: ```quizQuestions.children.forEach is not a function```

2021-11-15 17:31 UTC, cgduncan7 approved these changes

2021-11-15 17:32 UTC, merged