Timer for questions
cgduncan7/browser-quiz-project-starter pull request #11
Opened 2021-11-14 09:36 UTC by SaidYein

2021-11-14 10:57 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +  timerData.counter = setInterval(()=>{
Let's move this inner function to its own named function so it's a bit easier to read. Move everything related to the timer there and then we can call that function with the `setInterval` here

2021-11-14 14:51 UTC, SaidYein commented on src/handlers/questionHandlers.js
> +  timerData.counter = setInterval(()=>{
Hi Collin. Do you mean that I need to carry the function to Utils? If so, I had problems with passing parameters when I tried

2021-11-14 19:32 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +  timerData.counter = setInterval(()=>{
No It can be in handlers. You can pass parameters like `setInterval(() => timerFunction(param1, param2, ...))`

Or in this case `timerData.counter = setInterval(() => timerFunction(currentQuestion.time))`

2021-11-15 15:29 UTC, cgduncan7 requested changes

2021-11-15 15:29 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +  }
not exactly what I meant but okay

2021-11-15 15:29 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +      console.log(currentQuestion)
❌ 
```suggestion
```

2021-11-15 15:56 UTC, SaidYein commented on src/handlers/questionHandlers.js
> +      console.log(currentQuestion)
Actually I use debıgger but sometimes I need a quick peek to the data. That's the reason,  I swear 😄

2021-11-15 17:41 UTC, cgduncan7 approved these changes

2021-11-15 17:41 UTC, merged