Adding The References
cgduncan7/browser-quiz-project-starter pull request #7
Opened 2021-11-12 10:23 UTC by ChrisFayad

2021-11-12 13:05 UTC, cgduncan7 requested changes

2021-11-12 13:05 UTC, cgduncan7 commented on src/views/questionViews.js
> +  card_1.classList.add('card', 'card1');
Let's use a for-loop! What if we have more or less questions?

2021-11-12 13:05 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +let step = 10;
Why are these here? We should keep them into the scope in which they are required

2021-11-12 13:05 UTC, cgduncan7 commented on src/constants.js
> +export const inactive = document.getElementsByClassName("inactive")
These are not constants. Constant means it can never change but these will change. I would suggest moving these into the `DOMUtils` and making them functions like:

```javascript
export const getCardElements = () => document.getElementsByClassName('card');
export const getInactiveCardElements = () => document.getElementsByClassName('inactive');
```

Then you can use them as functions where you need to to get all active/inactive cards

2021-11-12 13:05 UTC, cgduncan7 commented on public/style.css
> +}
Lots of styling ✨

2021-11-12 13:07 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +  clearDOMElement(questionContainer);
I don't think we need to clear this right? Otherwise we will remove the question when adding references.

2021-11-12 13:07 UTC, cgduncan7 commented on src/views/questionViews.js
> +export const createReferenceElement = (linkData) => {
Nice reusable code 👍

2021-11-12 13:08 UTC, cgduncan7 commented
Nice work @ChrisFayad 👏 lots of good additions but I have a few suggestions to make it a bit more bulletproof 😄

2021-11-12 14:21 UTC, ChrisFayad commented on src/handlers/questionHandlers.js
> +let step = 10;
I'm not sure where to put these two lines of code
`let i=0;
let step = 10;`
I did put `document.getElementsByClassName('card1')` & `document.getElementsByClassName('card')` & `document.getElementsByClassName('inactive')` in DOMUtils

2021-11-12 14:25 UTC, ChrisFayad commented on src/handlers/questionHandlers.js
> +let step = 10;
https://codepen.io/chrisfayad/pen/rNzrGea
Can you please check this codepen .. here everything is working because the JS code all in one place .. but with the project structure I'm not sure where to declare `i` & `step` to be written only once, not every time we click on the next question button.

2021-11-12 14:43 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +let step = 10;
You can make another object in `src/data.js` and call it `animationData` and export this and use where it is needed

2021-11-13 11:07 UTC, cgduncan7 requested changes

2021-11-13 11:07 UTC, cgduncan7 commented on src/constants.js
> +export const inactive = document.getElementsByClassName("inactive")
@ChrisFayad these should be changed still

2021-11-13 11:22 UTC, ChrisFayad commented on src/constants.js
> +export const inactive = document.getElementsByClassName("inactive")
Sorry I thought I already removed them

2021-11-13 12:52 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +  clearDOMElement(questionContainer);
@ChrisFayad can you answer this question?

2021-11-13 12:56 UTC, cgduncan7 commented
@ChrisFayad now you'll need to resolve the conflicts listed below as well

2021-11-13 13:28 UTC, ChrisFayad commented on src/handlers/questionHandlers.js
> +  clearDOMElement(questionContainer);
No we don't need too

2021-11-13 13:33 UTC, ChrisFayad commented
@cgduncan7 I resolve the conflict .. however, there is a bug still because some questions has only one reference link not two .. but I think @AlexanderSaid  can fix that

2021-11-13 13:38 UTC, AlexanderSaid commented
I already build it, but I can't apply it without reorganize the creating and appending elements

2021-11-13 13:39 UTC, ChrisFayad commented
@AlexanderSaid Let's have a talk & I will tell you what's changed

2021-11-13 21:06 UTC, cgduncan7 requested changes

2021-11-13 21:06 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> -  button.addEventListener('click', nextQuestion);
This needs to be added back

2021-11-13 21:06 UTC, cgduncan7 commented on src/views/questionViews.js
> +  buttonElement.addEventListener('click', nextQuestion);
And this removed

2021-11-14 10:53 UTC, cgduncan7 approved these changes

2021-11-14 10:53 UTC, merged