added 5 new questions to data.js
cgduncan7/browser-quiz-project-starter pull request #8
Opened 2021-08-03 07:08 UTC by majidireshad

# Pull Request

> :arrow_right: Describe your pull request. Make sure to detail all changes and what the purpose of the PR is. PRs should be concise and only contain files related to the PR!

## Checklist

Complete these things in order to submit your PR for review:

- [x] :mag: I have manually checked the code in my changes
- [ ] :judge: I have tested my changes
- [ ] :pencil: I have provided comments in code to explain my changes

2021-08-03 09:15 UTC, cgduncan7 requested changes

2021-08-03 09:15 UTC, cgduncan7 commented on src/data.js
> +      text: 'Where is the correct place to insert a JavaScript?',
```suggestion
      text: 'Where is the correct place to insert JavaScript in HTML?',
```

2021-08-03 09:15 UTC, cgduncan7 commented on src/data.js
> +      text: ' --------------- method returns the number of milliseconds in a date string.',
```suggestion
      text: 'Which method returns the number of milliseconds in a date string?',
```

2021-08-03 09:15 UTC, cgduncan7 commented on src/data.js
> +      text: 'Who invented the javascript programming language?',
```suggestion
      text: 'Who invented the JavaScript programming language?',
```

2021-08-03 09:15 UTC, cgduncan7 commented on src/data.js
> +      text: 'Math.round(-20.5)=?',
```suggestion
      text: 'Math.round(-20.5) returns what?',
```

2021-08-03 10:40 UTC, majidireshad commented on src/data.js
> +      text: 'How do you delete an element from an options array?',
I might have not used the best source for questions. I replace this one with another one.

2021-08-03 13:51 UTC, cgduncan7 requested changes

2021-08-03 13:51 UTC, cgduncan7 commented on src/data.js
> +      correct: 'd',
```javascript
let x = 0
do {
  console.log(x++)
} while (x < 10)
```

is available in JavaScript 🙃

2021-08-03 13:51 UTC, cgduncan7 commented on src/data.js
> +      correct: 'd',
Maybe you could ask the team if they can help provide some possible questions?

2021-08-05 11:52 UTC, cgduncan7 commented
Closing in favor of https://github.com/cgduncan7/browser-quiz-project-starter/pull/13

2021-08-05 11:52 UTC, closed without merging