Lydia see correct answer
cgduncan7/browser-quiz-project-starter pull request #9
Opened 2021-08-04 00:38 UTC by Lydia-GG

# Pull Request

> :arrow_right: Describe your pull request. Make sure to detail all changes and what the purpose of the PR is. PRs should be concise and only contain files related to the PR!

## Checklist

Complete these things in order to submit your PR for review:

- [ ] :mag: I have manually checked the code in my changes
- [ ] :judge: I have tested my changes
- [ ] :pencil: I have provided comments in code to explain my changes

2021-08-04 06:14 UTC, cgduncan7 requested changes

2021-08-04 06:14 UTC, cgduncan7 commented on src/views/questionViews.js
> +      }
I don't think this is the correct place for this code! In the `README` for views it states that they will never use events! This is using an event 😄 

Where should you *handle* this event?

2021-08-04 06:14 UTC, cgduncan7 commented on src/views/questionViews.js
> +  answerElement.style.cursor = "pointer";
✨

2021-08-05 09:58 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +export const handleCheckAnswer = (selectedAnswer) => {
What is `selectedAnswer`?

2021-08-05 09:58 UTC, cgduncan7 commented on src/listeners/questionListeners.js
> +  handleCheckAnswer();
`handleCheckAnswer` takes one argument of `selectedAnswer` but you provide no argument!

2021-08-05 09:58 UTC, cgduncan7 commented on src/views/questionViews.js
> +    // })
```suggestion
```

2021-08-05 20:06 UTC, cgduncan7 submitted a review, later dismissed

2021-08-05 20:06 UTC, cgduncan7 commented on src/handlers/questionHandlers.js
> +let currentCorrectAnswer = currentQuestion.answers[currentQuestion.correct];
Nice one! This is perfect

2021-08-05 20:06 UTC, cgduncan7 commented on src/listeners/questionListeners.js
> +  handleCheckAnswer(event.target);
👍

2021-08-05 20:09 UTC, cgduncan7 commented
@Lydia-GG nice work 👏 now you need to resolve these merge conflicts! In VS Code you should:
```
git checkout master // checkout master branch
git pull // update master branch
git checkout Lydia-see-correct-answer // checkout your WIP branch
git merge master // merge changes from master into your branch
```

Then you will see conflicts in the above files ^

If you need help, let me know!

2021-08-05 22:18 UTC, Lydia-GG commented
> @Lydia-GG nice work 👏 now you need to resolve these merge conflicts! In VS Code you should:
> 
> ```
> git checkout master // checkout master branch
> git pull // update master branch
> git checkout Lydia-see-correct-answer // checkout your WIP branch
> git merge master // merge changes from master into your branch
> ```
> 
> Then you will see conflicts in the below files vvvv
> 
> If you need help, let me know!

2021-08-05 22:19 UTC, Lydia-GG commented
> > @Lydia-GG nice work 👏 now you need to resolve these merge conflicts! In VS Code you should:
> > ```
> > git checkout master // checkout master branch
> > git pull // update master branch
> > git checkout Lydia-see-correct-answer // checkout your WIP branch
> > git merge master // merge changes from master into your branch
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you will see conflicts in the below files vvvv
> > If you need help, let me know!

2021-08-06 06:40 UTC, cgduncan7 approved these changes
👏 🎆

2021-08-06 06:40 UTC, merged